# Generated by Django 5.2.15 on 2026-06-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0009_category_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
