# Generated by Django 5.2.15 on 2026-06-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0010_article_is_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ai_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
