# Generated by Django 5.2.15 on 2026-06-27 04:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0011_article_ai_summary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleBand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Band', max_length=255)),
                ('content', models.TextField(blank=True, default='')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bands', to='journal.article')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
