# Generated by Django 5.2.15 on 2026-06-30 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0012_articleband'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorial',
            options={'ordering': ['-created_at'], 'verbose_name': "Tahririyat a'zosi", 'verbose_name_plural': "Tahririyat a'zolari"},
        ),
    ]
