# Generated by Django 5.2.15 on 2026-06-30 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0013_alter_editorial_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='editorial',
            name='content',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='content_uz',
        ),
        migrations.AddField(
            model_name='editorial',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='editorial',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='editorial',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='editorial',
            name='position',
            field=models.CharField(default='', max_length=150),
        ),
        migrations.AddField(
            model_name='editorial',
            name='position_en',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='editorial',
            name='position_ru',
            field=models.CharField(default='', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='editorial',
            name='position_uz',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
