# Generated by Django 5.2.15 on 2026-07-02 04:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0014_remove_editorial_content_remove_editorial_content_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SitePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page_type', models.CharField(choices=[('maxfiylik', 'Maxfiylik siyosati'), ('nashr', 'Nashr etiketkasi')], max_length=20, unique=True, verbose_name='Sahifa turi')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Kontent (asosiy)')),
                ('content_uz', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name="Kontent (O'zbek)")),
                ('content_en', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Kontent (Ingliz)')),
                ('content_ru', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Kontent (Rus)')),
            ],
            options={
                'verbose_name': 'Sayt sahifasi',
                'verbose_name_plural': 'Sayt sahifalari',
            },
        ),
    ]
