# Generated by Django 5.2.15 on 2026-07-08 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0016_monument_timelineevent_submission'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monument',
        ),
        migrations.DeleteModel(
            name='TimelineEvent',
        ),
    ]
