# Generated by Django 5.2.15 on 2026-07-10 09:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0017_delete_monument_delete_timelineevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='articles/pdfs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])], verbose_name='PDF fayl'),
        ),
    ]
