# Generated by Django 5.2.15 on 2026-07-28 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0020_articlefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='journal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='articles', to='journal.journal', verbose_name='Jurnal soni'),
        ),
    ]
