# Generated by Django 5.2.15 on 2026-08-03 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0022_alter_article_pdf_file_alter_articlefile_pdf_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='YearCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('year', models.IntegerField(unique=True, verbose_name='Yil')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'year categories',
                'ordering': ['-year'],
            },
        ),
        migrations.RemoveField(
            model_name='journal',
            name='source_year',
        ),
        migrations.AddField(
            model_name='journal',
            name='year_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='journals', to='journal.yearcategory'),
        ),
    ]
