# Generated by Django 5.2.15 on 2026-08-04 05:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0023_yearcategory_remove_journal_source_year_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='author_description_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='author_description_ru',
        ),
        migrations.RemoveField(
            model_name='about',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='about',
            name='journal_name_en',
        ),
        migrations.RemoveField(
            model_name='about',
            name='journal_name_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='article',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='position_en',
        ),
        migrations.RemoveField(
            model_name='editorial',
            name='position_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='content_ru',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='sendingarticle',
            name='content_en',
        ),
        migrations.RemoveField(
            model_name='sendingarticle',
            name='content_ru',
        ),
        migrations.AlterField(
            model_name='journal',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='journal/files/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx'])]),
        ),
        migrations.AlterField(
            model_name='journal',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='journal/images/%Y/%m/%d/'),
        ),
    ]
