# Generated by Django 5.2.15 on 2026-08-04 05:45

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0024_remove_about_author_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='abstract',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Annotatsiya (Abstract)'),
        ),
        migrations.AddField(
            model_name='article',
            name='doi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='DOI'),
        ),
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name="Kalit so'zlar (Keywords)"),
        ),
        migrations.AddField(
            model_name='article',
            name='pages',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sahifalar (masalan: 84-91)'),
        ),
        migrations.AddField(
            model_name='article',
            name='references',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Foydalanilgan adabiyotlar (References)'),
        ),
    ]
