# Generated by Django 5.2.15 on 2026-08-05 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0025_article_abstract_article_doi_article_keywords_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='editorial',
            options={'ordering': ['position', 'first_name'], 'verbose_name': "Tahririyat a'zosi", 'verbose_name_plural': "Tahririyat a'zolari"},
        ),
        migrations.RemoveIndex(
            model_name='editorial',
            name='journal_edi_created_a35c6f_idx',
        ),
        migrations.AlterField(
            model_name='editorial',
            name='position',
            field=models.CharField(choices=[('bosh_muharrir', 'Bosh muharrir'), ('tahrir_azosi', "Tahrir hay'ati a'zosi")], default='tahrir_azosi', max_length=150),
        ),
        migrations.AlterField(
            model_name='editorial',
            name='position_uz',
            field=models.CharField(choices=[('bosh_muharrir', 'Bosh muharrir'), ('tahrir_azosi', "Tahrir hay'ati a'zosi")], default='tahrir_azosi', max_length=150, null=True),
        ),
        migrations.AddIndex(
            model_name='editorial',
            index=models.Index(fields=['position'], name='journal_edi_positio_47378f_idx'),
        ),
    ]
