# Generated by Django 5.2.15 on 2026-08-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0026_alter_editorial_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='editorial',
            name='description',
            field=models.TextField(blank=True, default='', verbose_name='Tavsif (unvon, daraja)'),
        ),
    ]
