# Generated by Django 5.2.15 on 2026-08-05 02:33

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0027_editorial_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='author_description_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='author_description_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='journal_name_en',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='about',
            name='journal_name_ru',
            field=models.CharField(max_length=127, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content_en',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='content_ru',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='article',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='editorial',
            name='position_en',
            field=models.CharField(choices=[('bosh_muharrir', 'Bosh muharrir'), ('tahrir_azosi', "Tahrir hay'ati a'zosi")], default='tahrir_azosi', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='editorial',
            name='position_ru',
            field=models.CharField(choices=[('bosh_muharrir', 'Bosh muharrir'), ('tahrir_azosi', "Tahrir hay'ati a'zosi")], default='tahrir_azosi', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sendingarticle',
            name='content_en',
            field=ckeditor.fields.RichTextField(null=True),
        ),
        migrations.AddField(
            model_name='sendingarticle',
            name='content_ru',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
