# Generated by Django 5.2.15 on 2026-08-07 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0028_about_author_description_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='published_date',
            field=models.DateField(blank=True, null=True, verbose_name='Nashr qilingan sana'),
        ),
    ]
