# Generated by Django 5.2.15 on 2026-08-07 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0029_article_published_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['start_page', '-created_at']},
        ),
        migrations.AddField(
            model_name='article',
            name='start_page',
            field=models.IntegerField(default=0, editable=False),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['start_page'], name='journal_art_start_p_ac8b82_idx'),
        ),
    ]
